const clientWork = [
  {slug:'healthcare-data',title:'Healthcare Data Quality Automation',tag:'Data Quality · Process Automation',metric:'250K records / batch',result:'6h → 2.5h review turnaround',desc:'Automated validation and exception reporting for high-volume healthcare data using Python, SQL and Power BI.'},
  {slug:'infinity-fitness',title:'Infinity Fitness Studios',tag:'Retention · Member Analytics',metric:'Direct client engagement',result:'Retention, cohorts & utilization',desc:'Turned a year of membership and operational data into decision-oriented retention and utilization analysis.'},
  {slug:'maintenance',title:'Maintenance Operations',tag:'Operations · Power BI',metric:'10K records · 20 teams',result:'3–4 hrs/week eliminated',desc:'Structured fragmented maintenance reporting into reusable operational visibility for management.'},
  {slug:'glamsquad',title:'The GlamSquad Salon',tag:'Profitability · Operations',metric:'15% profit increase',result:'Within ~2 months',desc:'Diagnosed declining profitability through staffing, pricing, appointment, service and customer analysis.'},
  {slug:'referme',title:'ReferMe Investments',tag:'Investment Analytics · KPI Framework',metric:'28 KPIs · 5 dimensions',result:'0–100 scoring framework',desc:'Designed a consistent investment evaluation framework and Power BI decision-support structure.'}
];

const skills = ['Requirements & BRD/FRD','User Stories & Acceptance Criteria','AS-IS / TO-BE','UAT & RTM','SQL','Power BI & DAX','Python','Excel & Power Query','Jira & Confluence','Trade Finance','LoanIQ','Root Cause Analysis'];

export default function Home(){return <main>
<header className="nav"><a className="brand" href="#home"><span>CS</span> Chinmayee Surwade</a><nav><a href="#about">About</a><a href="#experience">Experience</a><a href="#client-work">Client Work</a><a href="#portfolio">Portfolio</a><a href="#skills">Skills</a><a href="#contact">Contact</a></nav><a className="btn small" href="#contact">Let's Connect</a></header>
<section id="home" className="hero"><div className="heroCopy"><p className="eyebrow">BUSINESS ANALYST · DATA ANALYST · PROBLEM SOLVER</p><h1>Turning Business Problems into <em>Measurable Solutions</em></h1><p className="lead">4+ years across banking and independent consulting, working at the intersection of business analysis, data analytics and process improvement.</p><div className="actions"><a className="btn" href="#client-work">Explore My Work →</a><a className="ghost" href="#contact">Get in Touch</a></div></div><div className="portrait"><div className="photoPlaceholder"><strong>Professional portrait</strong><small>Your approved photo will be placed here at deployment</small></div><blockquote>“I enjoy understanding complex problems, finding the right questions and building solutions that actually make a difference.”</blockquote></div></section>
<section className="metrics"><div><b>4+</b><span>Years Experience</span></div><div><b>5+</b><span>Client Engagements</span></div><div><b>30%</b><span>UAT Defect Reduction</span></div><div><b>99%</b><span>On-Time Batch Completion</span></div></section>
<section id="client-work" className="section"><p className="eyebrow">INDEPENDENT CONSULTING & ANALYTICS</p><h2>Real Business Problems.<br/>End-to-End Analysis. <em>Measurable Outcomes.</em></h2><p className="intro">Selected freelance client engagements where I worked directly with business stakeholders to understand the problem, structure the data, perform analysis and translate findings into practical decisions.</p><div className="grid">{clientWork.map((p,i)=><article className="card" key={p.slug}><div className={'visual v'+i}><span>{String(i+1).padStart(2,'0')}</span></div><div className="cardBody"><p className="tag">{p.tag}</p><h3>{p.title}</h3><div className="caseMetric"><b>{p.metric}</b><span>{p.result}</span></div><p>{p.desc}</p><a href={'/case-studies/'+p.slug}>View Case Study →</a></div></article>)}</div></section>
<section id="experience" className="section split"><div><p className="eyebrow">PROFESSIONAL EXPERIENCE</p><h2>My Journey</h2></div><div className="timeline"><article><time>Jun 2024 – Present</time><h3>Independent Consultant · Business & Data Analytics</h3><p>Business analysis and analytics engagements across healthcare, fitness, maintenance, retail/service operations and investment analytics.</p></article><article><time>Jun 2022 – Jun 2024</time><h3>Software Engineer · BA Responsibilities</h3><p>Bank of America Continuum India · Trade Finance. Requirements, user stories, UAT, SQL validation, integrations and production support across critical applications.</p></article><article><time>2021</time><h3>Siemens · Internship</h3><p>Early professional experience in technology and data-oriented work.</p></article></div></section>
<section id="portfolio" className="section feature"><p className="eyebrow">PORTFOLIO SIMULATION</p><h2>Trade Finance Exception & Credit Utilization Control</h2><p>A synthetic-data Technical BA case study inspired by trade-finance domain experience. It demonstrates requirements, business rules, exception management, reconciliation, SQL validation, UAT and reporting without exposing confidential bank information.</p><div className="flow"><span>Trade Platform</span><i>→</i><span>Messaging</span><i>→</i><span>Credit Utilization</span><i>→</i><span>Exception Control</span></div></section>
<section id="skills" className="section"><p className="eyebrow">SKILLS & TOOLS</p><h2>Business thinking backed by <em>technical depth.</em></h2><div className="skillGrid">{skills.map(s=><span key={s}>{s}</span>)}</div></section>
<section id="about" className="section about"><div><p className="eyebrow">ABOUT ME</p><h2>Analytical Thinker.<br/>Problem Solver.<br/><em>Builder.</em></h2></div><div><p className="lead">I work across business processes, requirements and data. My approach starts with understanding what the business is actually trying to solve, then building enough structure to make the problem measurable and actionable.</p><p>My background combines banking and Trade Finance with independent consulting across multiple business domains.</p></div></section>
<section id="contact" className="section contact"><div><p className="eyebrow">GET IN TOUCH</p><h2>Let's Connect</h2><p>Open to Business Analyst, Technical BA and Data Analyst opportunities.</p></div><div className="contactCards"><a href="mailto:chinmayee.surwade@gmail.com"><b>Email Me</b><span>chinmayee.surwade@gmail.com</span></a><a href="https://www.linkedin.com/in/chinmayeesurwade/"><b>LinkedIn</b><span>Connect professionally</span></a><a href="https://github.com/chinmayeesurwade"><b>GitHub</b><span>View my work</span></a><div><b>Need to speak directly?</b><span>Request my phone number. I review requests before sharing private contact details.</span><a className="btn request" href="mailto:chinmayee.surwade@gmail.com?subject=Request%20for%20Phone%20Number&body=Name%3A%0ACompany%3A%0AWork%20Email%3A%0ARole%20%2F%20Opportunity%3A%0ALinkedIn%3A%0AReason%20for%20contact%3A">Request Phone Number →</a></div></div></section>
<footer><b>Chinmayee Surwade</b><span>Business Analyst · Data Analyst</span><small>© 2026 Chinmayee Surwade</small></footer>
</main>}
