import Base64Image from './components/Base64Image';

const clientWork=[
{slug:'healthcare-data',title:'Healthcare Data Quality',tag:'SQL · Python · Power BI',metric:'~250K',metricLabel:'records / batch',desc:'Data quality automation and exception reporting. Reduced review turnaround from 6 hours to 2.5 hours.'},
{slug:'infinity-fitness',title:'Infinity Fitness Studios',tag:'SQL · Power BI · Analytics',metric:'25+',metricLabel:'KPIs',desc:'Retention, cohort and utilization analysis built from direct stakeholder discovery.'},
{slug:'glamsquad',title:'The GlamSquad Salon',tag:'Excel · Power BI · BA',metric:'15%',metricLabel:'profit increase',desc:'Profitability and operations analysis across appointments, services and staffing.'},
{slug:'maintenance',title:'Maintenance Operations',tag:'SQL · Power BI · Process',metric:'92%',metricLabel:'completion rate',desc:'Operational reporting across ~10K historical records and 20 teams.'},
{slug:'referme',title:'ReferMe Investments',tag:'Python · Power BI · Analytics',metric:'28',metricLabel:'KPIs',desc:'Traceable investment evaluation framework across five business dimensions.'}
];
const skills=[
{icon:'▣',title:'BA & Process',text:'Jira, Confluence, Visio, BPMN, RTM, UAT'},
{icon:'▥',title:'Data & Analytics',text:'SQL, Python, Power BI, Tableau, Excel'},
{icon:'◇',title:'Banking & Trade Finance',text:'LoanIQ, Tradeline, CashPro Trade, SWIFT'},
{icon:'⬡',title:'Development & DevOps',text:'Git, Azure DevOps, ServiceNow, MQ'},
{icon:'✦',title:'AI & GenAI',text:'Gemini, RAG, ChromaDB, Streamlit'},
{icon:'◎',title:'Soft Skills',text:'Communication, Stakeholder Management, Problem Solving'}
];
function MiniChart({type=0}){return <div className={'miniChart chart'+type}><div className="chartKpis"><i/><i/><i/></div><div className="chartArea"><span/><span/><span/><span/><span/><span/></div></div>}
export default function Home(){return <main className="referenceHome">
<header className="nav refNav"><a className="brand" href="#home"><span>CS</span><div><b>Chinmayee Surwade</b><small>Business Analyst | Data Analyst | Problem Solver</small></div></a><nav><a href="#home">Home</a><a href="#experience">Experience</a><a href="#client-work">Client Work</a><a href="#portfolio">Simulations</a><a href="#skills">Skills</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="ghost resumeTop" href="mailto:chinmayee.surwade@gmail.com?subject=Resume%20Request">↓ &nbsp; Download Resume</a></header>
<section id="home" className="hero refHero"><div className="heroCopy"><p className="eyebrow">BUSINESS ANALYST · TECHNICAL BA · DATA ANALYST</p><h1>I turn complex<br/>business problems<br/>into <em>clear, measurable<br/>solutions.</em></h1><p className="lead">4+ years across banking and independent consulting. I combine requirements, process analysis and data to help teams understand what is happening, why it is happening and what to do next.</p><div className="actions"><a className="btn" href="#client-work">View My Work &nbsp; →</a><a className="ghost" href="mailto:chinmayee.surwade@gmail.com?subject=Resume%20Request">↓ &nbsp; Download Resume</a></div><div className="heroMeta"><span>⌖ Chennai, India (Open to Relocate)</span><span>▣ Immediate Joiner</span><a href="mailto:chinmayee.surwade@gmail.com">✉</a><a href="https://www.linkedin.com/in/chinmayeesurwade/">in</a><a href="https://github.com/chinmayeesurwade">●</a></div></div><div className="portrait refPortrait"><div className="portraitGlow"/><div className="portraitFrame"><Base64Image src="/assets/portrait.b64" alt="Professional portrait of Chinmayee Surwade" className="portraitPhoto"/></div><div className="heroQuote"><b>“</b><p>Start with the business problem.<br/>Make the logic traceable.<br/>Use data to support the decision.</p><i/><strong>Chinmayee Surwade</strong><small>Business Analyst | Data Analyst</small></div></div></section>
<section className="metrics refMetrics"><div><span className="metricIcon">⚙</span><p><b>30%</b><small>UAT defect reduction</small></p></div><div><span className="metricIcon">◷</span><p><b>99%</b><small>On-time batch delivery</small></p></div><div><span className="metricIcon">♙</span><p><b>15+</b><small>User stories authored</small></p></div><div><span className="metricIcon">▤</span><p><b>5+</b><small>Client engagements</small></p></div><div><span className="metricIcon">⌁</span><p><b>250K+</b><small>Records validated</small></p></div></section>
<section id="client-work" className="compactSection"><div className="sectionTitle"><div><h2>Client Work</h2><p>Real engagements. Clear business problems. Evidence-backed outcomes.</p></div><a href="#client-work">View All Client Work →</a></div><div className="clientRow">{clientWork.map((p,i)=><a className="compactCard" key={p.slug} href={'/case-studies/'+p.slug}><MiniChart type={i}/><h3>{p.title}</h3><p>{p.desc}</p><div className="compactMetric"><b>{p.metric}</b><span>{p.metricLabel}</span></div><div className="chips">{p.tag.split(' · ').map(t=><span key={t}>{t}</span>)}</div></a>)}</div></section>
<section id="portfolio" className="compactSection"><div className="sectionTitle"><div><h2>Portfolio Simulations</h2><p>Domain-inspired case studies demonstrating business analysis and systems thinking.</p></div><a href="#portfolio">View All Simulations →</a></div><div className="simulationRow"><a className="simulationCard trade" href="/portfolio/trade-finance-control"><div><h3>Trade Finance Exception & Credit Utilization Control</h3><small>Domain: Banking & Trade Finance</small><p>Exception handling, reconciliation, business rules, process maps, dashboards, RTM and UAT using fictional systems and synthetic data.</p><div className="chips"><span>Process Design</span><span>SQL</span><span>Power BI</span><span>BA</span></div></div><b>View Case Study →</b></a><a className="simulationCard health" href="/portfolio/healthcare-payer"><div><h3>Healthcare Payer Portal Automation</h3><small>Domain: Healthcare</small><p>Portal variation mapping, common taxonomy, source-to-target rules, exception design and human-review boundaries.</p><div className="chips"><span>Process Mapping</span><span>Data Analysis</span><span>Business Rules</span><span>BA</span></div></div><b>View Case Study →</b></a></div></section>
<section id="experience" className="compactSection"><div className="sectionTitle"><h2>Professional Experience</h2><a href="#experience">View Full Experience →</a></div><div className="experienceCards"><article><div className="companyLogo boa">BA</div><div className="experienceBody"><div className="experienceHead"><div><h3>Software Engineer (Business Analysis)</h3><p>Bank of America Continuum India Pvt. Ltd.</p></div><span>Chennai, India<br/>Jun 2022 – Jun 2024</span></div><ul><li>Worked in Trade Finance across LoanIQ, Tradeline and CashPro Trade.</li><li>Gathered requirements, created BRD/FRD, user stories and UAT scenarios.</li><li>Supported MQ migration and monitored six critical applications.</li><li>Reduced UAT defects by ~30% and sustained 99% on-time batch completion.</li></ul></div></article><article><div className="companyLogo siemens">S</div><div className="experienceBody"><div className="experienceHead"><div><h3>Internship</h3><p>Siemens</p></div><span>2021</span></div><ul><li>Early professional exposure to technology delivery.</li><li>Built experience working in an enterprise environment.</li><li>Developed a foundation for subsequent business and technical analysis work.</li></ul></div></article></div></section>
<section id="skills" className="compactSection skillsSection"><div className="sectionTitle"><h2>Skills & Tools</h2><a href="#skills">View All Skills →</a></div><div className="skillStrip">{skills.map(s=><div key={s.title}><span>{s.icon}</span><p><b>{s.title}</b><small>{s.text}</small></p></div>)}</div></section>
<section id="about" className="compactSection aboutCompact"><h2>How I Work</h2><p>Understand the current state. Structure the problem. Make requirements and business rules traceable. Validate the answer with data. Communicate what changes and why.</p></section>
<footer id="contact" className="refFooter"><div><b>Chinmayee Surwade</b><span>Turning data and requirements into real business impact.</span></div><nav><a href="https://www.linkedin.com/in/chinmayeesurwade/">LinkedIn</a><a href="https://github.com/chinmayeesurwade">GitHub</a><a href="mailto:chinmayee.surwade@gmail.com">Email</a></nav><small>© 2026 Chinmayee Surwade. All rights reserved.</small></footer>
</main>}
