import PDFDocument from 'pdfkit';
export const runtime='nodejs';
export async function GET(){
 const doc=new PDFDocument({size:'A4',margin:42,info:{Title:'Chinmayee Surwade Resume',Author:'Chinmayee Surwade'}});const chunks=[];doc.on('data',c=>chunks.push(c));const done=new Promise(r=>doc.on('end',r));
 const section=t=>{doc.moveDown(.55).font('Helvetica-Bold').fontSize(11).fillColor('#123b63').text(t.toUpperCase());doc.moveTo(42,doc.y+2).lineTo(553,doc.y+2).strokeColor('#b8c7d5').stroke();doc.moveDown(.45)};
 const bullet=t=>doc.font('Helvetica').fontSize(8.7).fillColor('#202b35').text('• '+t,{indent:8,lineGap:1.5});
 doc.font('Helvetica-Bold').fontSize(20).fillColor('#102a43').text('CHINMAYEE SURWADE',{align:'center'});doc.font('Helvetica').fontSize(9).fillColor('#34495e').text('Business Analyst | Data Analyst | Trade Finance & Banking Systems',{align:'center'});doc.fontSize(8.5).text('Chennai, India | chinmayee.surwade@gmail.com | linkedin.com/in/chinmayeesurwade | github.com/chinmayeesurwade',{align:'center'});
 section('Profile');doc.font('Helvetica').fontSize(8.8).fillColor('#202b35').text('Business Analyst and Data Analyst with 4+ years of experience across banking operations and independent data consulting. Two years at Bank of America Continuum India delivering trade finance systems, with experience in requirements, UAT, process analysis, SQL validation, Power BI and stakeholder management. Immediate joiner.',{lineGap:2});
 section('Core Skills');doc.fontSize(8.5).text('Business Analysis: Requirements Gathering, Stakeholder Management, BRD, FRD, SRS, User Stories, Acceptance Criteria, UAT, Gap Analysis, BPMN, RTM');doc.text('Data & Analytics: SQL, Python, Power BI, Tableau, Advanced Excel, KPI Reporting, Data Validation');doc.text('Banking & Systems: Trade Finance, Letters of Credit, Documentary Collections, Open Account, LoanIQ, MQ Messaging, Transaction Processing');doc.text('Tools & Methods: Jira, Azure DevOps, Confluence, Visio, Lucidchart, Agile, Waterfall, SDLC, ITIL Basics');
 section('Professional Experience');doc.font('Helvetica-Bold').fontSize(9.5).text('Independent Consultant | Business & Data Analytics                                      Jun 2024 – Present');bullet('Healthcare Data Client: automated data-quality checks across approximately 250,000 records per batch, surfacing a 2% observed exception rate and reducing review turnaround from 6 hours to 2.5 hours.');bullet('ReferMe Investments: designed an investment evaluation framework with 28 KPIs across five business dimensions and traceable Power BI decision-support views.');bullet('Infinity Fitness Studios: built retention and utilization analysis using SQL, Python and Power BI, with 25+ KPIs supporting operational decisions.');bullet('The GlamSquad Salon: diagnosed profitability drivers across staffing, pricing and customer behavior; implemented recommendations contributed to a documented 15% profit increase.');bullet('Maintenance Operations: structured approximately 10,000 historical records across 20 teams into Power BI reporting, surfacing a 92% observed completion rate and eliminating 3–4 hours of weekly manual reporting.');
 doc.moveDown(.45).font('Helvetica-Bold').fontSize(9.5).text('Bank of America Continuum India Pvt. Ltd. | Trade Finance & BAU                  Jun 2022 – Jun 2024');bullet('Gathered functional requirements for Letter of Credit, Documentary Collections and Open Account flows, translating them into 15+ user stories with acceptance criteria.');bullet('Coordinated across development, QA, operations and risk to validate transaction flows, reducing UAT defects by approximately 30%.');bullet('Supported Tradeline–LoanIQ integration and MQ messaging for near-real-time commitment utilization reporting.');bullet('Monitored nightly batch execution across six critical applications, sustaining 99% on-time completion.');bullet('Led UAT activities, SQL-based validation, defect triage, KPI reporting and stakeholder communication.');
 doc.moveDown(.45).font('Helvetica-Bold').fontSize(9.5).text('Siemens | Data Analyst Intern                                                        May 2021 – Oct 2021');bullet('Analyzed operational datasets in Excel, prepared KPI reporting and performed data cleaning and transformation.');
 section('Selected Portfolio Work');bullet('Trade Finance Exception & Credit Utilization Control: synthetic portfolio simulation covering exception handling, reconciliation, business rules, RTM, UAT and dashboards.');bullet('Healthcare Payer Portal Automation: synthetic portfolio simulation covering portal variation mapping, common taxonomy, source-to-target rules, exception design and human-review boundaries.');
 section('Education');doc.font('Helvetica-Bold').fontSize(9).text("B.Tech, Information Technology | MKSSS's Cummins College of Engineering for Women | 2022");
 doc.end();await done;const pdf=Buffer.concat(chunks);return new Response(pdf,{headers:{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="Chinmayee_Surwade_Resume.pdf"','Cache-Control':'public, max-age=3600'}})
}
